// Generated by scripts/sync_memories.py; do not edit manually.
window.MEMORIES_ALBUM = {
  "folderUrl": "https://drive.google.com/drive/folders/1zW14fybVorXE-Bq8KNrZCPvHCgvftYWb",
  "photos": [
    {
      "src": "https://drive.google.com/thumbnail?id=1NwUIbq9CcGCkcza1lqaUgpyHtuYadaxw&sz=w1600",
      "alt": "Our memories, photo 1",
      "caption": "Memory 1",
      "driveUrl": "https://drive.google.com/file/d/1NwUIbq9CcGCkcza1lqaUgpyHtuYadaxw/view"
    },
    {
      "src": "https://drive.google.com/thumbnail?id=17Rbvu39wpw0iF0LHzQJHvlY8vG0sHUc0&sz=w1600",
      "alt": "Our memories, photo 2",
      "caption": "Memory 2",
      "driveUrl": "https://drive.google.com/file/d/17Rbvu39wpw0iF0LHzQJHvlY8vG0sHUc0/view"
    }
  ]
};
