"""Refresh the gallery from CONFIG.MEMORIES.DRIVE_FOLDER_URL (public folder).
Run: python3 scripts/sync_memories.py
No credentials or manually maintained photo list are required.
"""
from pathlib import Path
import json
import re
import urllib.request

ROOT = Path(__file__).resolve().parents[1]

def read_folder(url):
    request = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
    with urllib.request.urlopen(request, timeout=30) as response:
        html = response.read().decode('utf-8')
    match = re.search(r"window\['_DRIVE_ivd'\] = '((?:\\.|[^'])*)'", html)
    if not match:
        raise RuntimeError('Cannot read the public folder. Check Anyone with the link access.')
    data = re.sub(r'\\x([0-9a-fA-F]{2})', lambda m: chr(int(m[1], 16)), match[1])
    return json.loads(data.replace('\\/', '/'))[0] or []

def main():
    config = (ROOT / 'js/invitation.js').read_text()
    match = re.search(r"DRIVE_FOLDER_URL:\s*'([^']+)'", config)
    if not match or not re.fullmatch(r'https://drive\.google\.com/drive/folders/[\w-]+', match[1]):
        raise RuntimeError('Set DRIVE_FOLDER_URL to a public Google Drive folder URL.')
    url = match[1]
    entries = read_folder(url)
    photos = []
    for entry in entries:
        if not entry[3].startswith('image/'):
            continue
        file_id = entry[0]
        if not re.fullmatch(r'[\w-]+', file_id):
            continue
        photos.append({
            'src': f'https://drive.google.com/thumbnail?id={file_id}&sz=w1600',
            'alt': f'Our memories, photo {len(photos) + 1}',
            'caption': f'Memory {len(photos) + 1}',
            'driveUrl': f'https://drive.google.com/file/d/{file_id}/view'
        })
    if not photos:
        raise RuntimeError('No publicly readable images found; existing gallery retained.')
    payload = {'folderUrl': url, 'photos': photos}
    target = ROOT / 'js/memories-data.js'
    temporary = target.with_suffix('.tmp')
    temporary.write_text('// Generated by scripts/sync_memories.py; do not edit manually.\nwindow.MEMORIES_ALBUM = ' + json.dumps(payload, ensure_ascii=True, indent=2) + ';\n')
    temporary.replace(target)
    print(f'Gallery refreshed: {len(photos)} photos from the public Drive folder.')

if __name__ == '__main__':
    main()
